### ISSUE TITLE
exited with code 0

### ISSUE THREAD

**Issue by heuzef** [duo/matrix-wechat-docker#2]
Hi :)
Sorry it's kinda hard to understand what's is wrong when i started the containers.

你好 :)
抱歉，当我启动 containers 时，有点难以理解出了什么问题。

```
agent-wechat-hongli  | Start agent manager...
agent-wechat-hongli  | Initialize agent...
agent-wechat-hongli  | Download agent
agent-wechat-hongli  | cp: 无法创建普通文件'/home/user/matrix-wechat-agent/matrix-wechat-agent.exe': 权限不够
agent-wechat-hongli  | Download dll
agent-wechat-hongli  | cp: 无法创建普通文件'/home/user/matrix-wechat-agent/SWeChatRobot.dll': 权限不够
agent-wechat-hongli  | cp: 无法创建普通文件'/home/user/matrix-wechat-agent/wxDriver64.dll': 权限不够
agent-wechat-hongli  | cp: 无法创建普通文件'/home/user/matrix-wechat-agent/wxDriver.dll': 权限不够
agent-wechat-hongli  | Start vnc...
agent-wechat-hongli  | Start agent...
agent-wechat-hongli  | A X11 server is already running for display :5 on machine agent-wechat-hongli.
agent-wechat-hongli  |
agent-wechat-hongli  | Warning: agent-wechat-hongli:5 is taken because of /tmp/.X11-unix/X5
agent-wechat-hongli  | Remove this file if there is no X server agent-wechat-hongli:5
agent-wechat-hongli  |
agent-wechat-hongli  | Warning: agent-wechat-hongli:5 is taken because of /tmp/.X5-lock
agent-wechat-hongli  | Remove this file if there is no X server agent-wechat-hongli:5
agent-wechat-hongli  | �޷��� "/home/user/matrix-wechat-agent/matrix-wechat-agent.exe -h wss://matrix-wechat/_wechat/ -s foobar" ʶ��Ϊ�ڲ����ⲿ�������������ű���
agent-wechat-hongli  |
agent-wechat-hongli exited with code 0
```

**Comment by heuzef** [comment]
My compose config :

```
  # Wechat bridge
  matrix-wechat: 
    image: lxduo/matrix-wechat
    container_name: matrix-wechat
    hostname: matrix-wechat
    restart: unless-stopped
    volumes:
      - /home/heuzef/matrix/bridges/wechat/data:/data
    ports:
      - 17778:17778/tcp
    depends_on:
      - synapse


  # Wechat agent Hongli
  agent-wechat-hongli: 
    image: lxduo/matrix-wechat-docker
    container_name: agent-wechat-hongli
    hostname: agent-wechat-hongli
    restart: unless-stopped
    environment:
      - WECHAT_HOST=wss://matrix-wechat/_wechat/
      - WECHAT_SECRET=foobar
    volumes:
      - /home/heuzef/matrix/bridges/wechat/hongli/:/home/user/matrix-wechat-agent
    depends_on:
```
